export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGIN_CHANGE = 'AUTH_LOGIN_CHANGE';
export const AUTH_PASSWORD_CHANGE = 'AUTH_PASSWORD_CHANGE';