export const RESET = 'RESET'

export const LOAD_START = 'LOAD_START';
export const LOAD_ERROR = 'LOAD_ERROR';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGIN_CHANGE = 'AUTH_LOGIN_CHANGE';
export const AUTH_PASSWORD_CHANGE = 'AUTH_PASSWORD_CHANGE';


export const PRODUCTS_FETCH = 'PRODUCTS_FETCH';

export const ADMIN_ADD = 'ADMIN_ADD'
export const ADMIN_ADD_SUCCESS = 'ADMIN_ADD_SUCCESS';
export const ADMIN_ADD_ERROR = 'ADMIN_ADD_ERROR';


export const ADMIN_EDIT_SUCCESS = 'ADMIN_EDIT_SUCCESS';
export const ADMIN_EDIT_ERROR = 'ADMIN_EDIT_ERROR';

export const ADMIN_PRODUCTS_ADD = 'ADMIN_PRODUCTS_ADD';
export const ADMIN_PRODUCTS_ADD_SUCCESS = 'ADMIN_PRODUCTS_ADD_SUCCESS';
export const ADMIN_PRODUCTS_ADD_ERROR = 'ADMIN_PRODUCTS_ADD_ERROR';

export const ADMIN_PRODUCTS_DELETE_SUCCESS = 'ADMIN_PRODUCTS_DELETE_SUCCESS'
export const ADMIN_PRODUCTS_DELETE_ERROR = 'ADMIN_PRODUCTS_DELETE_ERROR'



export const ADMIN_CATEGORIES_ADD = 'ADMIN_CATEGORIES_ADD';
export const ADMIN_CATEGORIES_ADD_SUCCESS = 'ADMIN_CATEGORIES_ADD_SUCCESS';
export const ADMIN_CATEGORIES_ADD_ERROR = 'ADMIN_CATEGORIES_ADD_ERROR';


export const CATEGORIES_FETCH = 'CATEGORIES_FETCH';


export const PRODUCTS_SEARCH = 'PRODUCTS_SEARCH';
export const PRODUCTS_SEARCH_EDIT = 'PRODUCTS_SEARCH_EDIT';
export const PRODUCTS_SEARCH_RESET = 'PRODUCTS_SEARCH_RESET';

export const PRODUCTS_SORT = 'PRODUCTS_SORT'

export const CART_EDIT = 'CART_EDIT';